Pavel to develop
50ohmTech/SummerSweat pull request #69
Opened 2018-10-04 10:52 UTC by 50rubasov

Сделана View без расчета импедансов и изменения номиналов

2018-10-07 17:34 UTC, Nachyn requested changes
Закрой кобоБоксы чтоб нельзя было вводить значения DropDownStyle = DropDownList
Во многих местах падает из-за необработанных исключений, например Добавить в R L C новый узел.

2018-10-07 17:34 UTC, Nachyn commented on Pavel/SummerPractice.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CircuitView", "..\..\Всё для вас\MainForm\CircuitView.csproj", "{BAE7E8DD-7CBD-44D1-ABAB-623EBD52EFF9}"
(не удалось загрузить файл проекта. Не удалось найти часть пути "*\repos\Всё для вас\MainForm\CircuitView.csproj")
Открой решение, в решении удали данный проект, добавь существующий рабочий проект.

2018-10-07 17:34 UTC, Nachyn commented on Pavel/View/CircuitMainForm.cs
> +            if (SelectingCircuitComboBox.SelectedIndex == 1)
не стоит сравнивать с конкретным значением, так как расположение элементов в комбо боксе может измениться, необходимо сравнивать например с Объектом if(_comboBox.SelectedItem is ComboBoxItem item) [ComboBoxItem - твой кастомный класс]

2018-10-07 17:34 UTC, Nachyn commented on Pavel/View/CircuitMainForm.cs
> +            if (NodeComboBox.SelectedItem == "L")
тоже самое

2018-10-10 17:11 UTC, YulyaNovichkova commented on Pavel/View/CircuitMainForm.cs
> +    public partial class MainForm : Form
XML

2018-10-10 17:11 UTC, YulyaNovichkova commented on Pavel/View/CircuitMainForm.cs
> +        private uint _resistorIterator;
XML

2018-10-11 02:51 UTC, YulyaNovichkova commented
Проект не открывается должным образом, View нет.

2018-10-18 05:39 UTC, andreygolubkow commented
D:\Projects\Всё для вас\MainForm\CircuitView.csproj : error  : не удалось загрузить файл проекта. Не удалось найти часть пути "D:\Projects\Всё для вас\MainForm\CircuitView.csproj".  D:\Projects\Всё для вас\MainForm\CircuitView.csproj

2018-10-23 10:32 UTC, closed without merging