Исправил замечания от Юли и А.Е.
50ohmTech/SummerSweat pull request #71
Opened 2018-10-17 14:06 UTC by voitje

Готовая программа. Исправил замечания от QA. Проверять без отрисовки (дабы не создать большие проверки).

2018-10-17 20:35 UTC, goryainovalex commented
Оставил замечания в коде (см. последний коммит в ветке).

2018-10-18 05:35 UTC, andreygolubkow commented on Igor/Model/Subcircuit.cs
> +        ///
Где?

2018-10-18 05:35 UTC, andreygolubkow commented on Igor/View/ImpedanceForm.cs
> +                    "-быть большим 0.000 000 1 по модулю\n " +
Мб эти правила в отдельное место вынести?

2018-10-18 05:47 UTC, YulyaNovichkova requested changes
1.Пустое место над кнопкой удалить
2.При ошибочном добавлении элемента имя элемента все равно присваивает имя элементу
(Три раза вышла ошибка при добавлении, а потом когда добавили корректно имя резистора получилось R4)
3.Окно с изменением значения лучше выводить в центр экрана
4.При выборе тестовых цепей, старая(первая выбранная) цепь остается а новая не отображается.
5.В значение при добавлении элемента нужно добавить ограничение.(не при изменении а при добавлении в текстбокс значения)
6.Растягивание окна немного косячное(вбок норм растягивается, вверх вниз нет)
7.В выборе тестовых цепей в комбобоксе поставь цепь которая будет отображаться по дефолту(допустим 1ю).

2018-10-20 08:20 UTC, DmitryKozhin commented on Igor/Model/TreeINode.cs
> +                    Text = $"({resistor.Name}) [{resistor.Value}]";
Если присутствует много однотипной генерации строк, то может быть стоит вынести это в отдельный метод и осуществлять операции над строками при помощи StringBuilder? (при подобном сценарии использования это эффективнее)

2018-10-20 08:20 UTC, DmitryKozhin commented on Igor/View/CircuitMainForm.cs
> +        private Dictionary<char, int> nameOfElements;
именование поля не по rsdn

2018-10-20 08:20 UTC, DmitryKozhin commented on Igor/View/CircuitMainForm.cs
>              if (NominalTextBox.Text == "")
string.IsNullOrEmpty()

2018-10-20 08:20 UTC, DmitryKozhin commented on Igor/Model/TreeINode.cs
> +                    Text = $"({resistor.Name}) [{resistor.Value}]";
Это просто рекомендация

2018-10-21 06:09 UTC, voitje commented on Igor/View/CircuitMainForm.cs
>              if (NominalTextBox.Text == "")
Исправил.

2018-10-21 06:09 UTC, voitje commented on Igor/View/CircuitMainForm.cs
> +        private Dictionary<char, int> nameOfElements;
Исправил.

2018-10-21 06:12 UTC, voitje commented on Igor/Model/TreeINode.cs
> +                    Text = $"({resistor.Name}) [{resistor.Value}]";
Все это будет вынесено в функцию, но количество код увеличиться, а по идее повторение то де будет. Потом для себя протестю, за рекомендацию спасибо.

2018-10-21 06:12 UTC, voitje commented on Igor/Model/Subcircuit.cs
> +        ///
Добавил

2018-10-21 06:13 UTC, voitje commented on Igor/View/ImpedanceForm.cs
> +                    "-быть большим 0.000 000 1 по модулю\n " +
Вынес функцию в отдельное место

2018-10-21 07:34 UTC, YulyaNovichkova commented
1. В форме расчета импеданса, при некорректном вводе числа, сообщение об ошибке выходит 2 раза подряд.
2. Всё окна сделать в центре экрана
3. Всё в этой же форме, когда начало больше границы, можно сделать сообщение о том, что должно быть наоборот
4. Всё там же, в датагриде лучше убрать первую пустую строку
5. Убери возможность делать строки шире в датагриде
6. Не исправлено 7-ое замечание с прошлой проверки
7. Исчезает отрисовка, например, когда параллельному соединению добавляешь параллельное соединение. Она возвращается, если добавить просто элемент.
8. Ты вообще убрал расширение формы. Теперь, если цепь будет большая, нет возможности 
 осмотреть ее всю.
9. При изменении значения элемента, окошечко не закрывается(только при самостоятельном закрытии), а выбрать другой элемент для изменения нет возможности.
10. Например, если в первую тестовую цепь, я в первое ПОСЛЕДОВАТЕЛЬНОЕ соединение пытаюсь добавить КАТУШКУ, то магическим образом там появляется сначала РЕЗИСТОР.
Далее с этим же элементом я нажимаю кнопку "Добавить" и наконец-то КАТУШКА, а потом уже конденсатор. Потом стабильно катушка. Короче, так во многих местах, ты знаешь, что делать)))

2018-10-22 15:05 UTC, YulyaNovichkova commented
1. При запуске программы, в комбобоксе отображается цепь№1, но в treeview ее нет. Либо отобразить ее там, либо в комбобоксе добавить поле "Своя цепь", тогда пусте tree будет оправдано.
2. Почему элементы цепи вдруг стали на английском, когда все остальное на русском?
3. Сразу при попытке добавления первой связи, вы ходит ошибка, из-за чего я не могу сделать СВОЮ цепь с нуля.
4. В принципе у тебя перестало работать, даже в готовые цепи не могу ничего добавить.

2018-10-23 13:43 UTC, YulyaNovichkova commented
1. В пустой цепи при нажатии "удалить", вместо упавшей ошибки, упавшая прога.
2. В расчете импеданса, ввожу в "начало" 10, а "границу" написать не могу, не дает месаджбокс.
3. Если всё так же цепи нет, то при нажатии "Расчитать", падает прога, а не ошибка.

2018-10-24 02:43 UTC, YulyaNovichkova approved these changes

2018-10-24 07:09 UTC, goryainovalex commented
Оставил замечания по коду в последнем коммите. См. TODO

2018-10-24 17:16 UTC, merged